spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://34.64.235.236:1962/federate_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: 1234
