spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k7d107.p.ssafy.io:3306/ebs_business?characterEncoding=UTF-8&serverTimezone=UTC
    username: d107
    password: gumi107

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

#JWT settings
jwt:
  access:
    expiration: '90'
    subject: Ebs AccessToken
  refresh:
    subject: Ebs RefreshToken
    expiration: '180'
  secret: S0f7AZxciEDA4asdRYUBohQukyrttdGdzv7xcvRneXo