#Google OAuth settings
google:
  client:
    id: 466872041505-7jo7kpr1tn4h1l8venup3u2vm9dgp0ec.apps.googleusercontent.com
#JWT
jwt:
  access:
    expiration: '90'
    subject: IEng AccessToken
  refresh:
    subject: IEng RefreshToken
    expiration: '180'
  secret: S0f7AZx5HIFA4NV0yiToZyQCLtrmJ_GAGc2t_6fFVXA
# database setting
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k7d107.p.ssafy.io:13107/ebs?characterEncoding=UTF-8&serverTimezone=UTC
    username: d107
    password: gumi107
#    url: jdbc:mariadb://localhost:3306/theground?characterEncoding=UTF-8&serverTimezone=UTC
#    username: ssafy
#    password: ssafy

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
  jackson:
    time-zone: Asia/Seoul
